export const SHOES = [
  {
    id: "jordan-1",
    name: "Air Jordan 1",
    colorway: "Chicago",
    year: "1985",
    price: "¥1,399",
    category: "篮球",
    silhouette: "jordan",
    blurb: "红白黑三色奠定传奇。高帮全粒面皮革，飞人元年配色，环视可见侧翼与领口滚边。",
    facts: ["高帮领口", "侧翼锁定", "硫化外底"],
    colorways: [
      {
        id: "chicago",
        label: "Chicago",
        swatch: "#C8102E",
        palette: {
          upper: "#C8102E",
          overlay: "#111111",
          quarter: "#C8102E",
          swoosh: "#111111",
          midsole: "#F4F1EA",
          outsole: "#111111",
          lace: "#F4F1EA",
          collar: "#111111",
          tongue: "#C8102E",
          toe: "#F4F1EA",
          lining: "#1A1A1A",
        },
      },
      {
        id: "royal",
        label: "Royal",
        swatch: "#1D4ED8",
        palette: {
          upper: "#1D4ED8",
          overlay: "#111111",
          quarter: "#1D4ED8",
          swoosh: "#111111",
          midsole: "#F4F1EA",
          outsole: "#111111",
          lace: "#F4F1EA",
          collar: "#111111",
          tongue: "#1D4ED8",
          toe: "#F4F1EA",
          lining: "#1A1A1A",
        },
      },
      {
        id: "shadow",
        label: "Shadow",
        swatch: "#6B7280",
        palette: {
          upper: "#6B7280",
          overlay: "#111111",
          quarter: "#6B7280",
          swoosh: "#111111",
          midsole: "#F4F1EA",
          outsole: "#111111",
          lace: "#E5E7EB",
          collar: "#111111",
          tongue: "#4B5563",
          toe: "#D1D5DB",
          lining: "#1A1A1A",
        },
      },
    ],
  },
  {
    id: "af1",
    name: "Air Force 1",
    colorway: "Triple White",
    year: "1982",
    price: "¥799",
    category: "生活",
    silhouette: "force",
    blurb: "球场到街头的原型。厚实中底与打孔鞋头，绕一圈看清杯型外底的圆弧。",
    facts: ["打孔鞋头", "杯型外底", "Pivot 圆盘"],
    colorways: [
      {
        id: "white",
        label: "Triple White",
        swatch: "#F8F5EF",
        palette: {
          upper: "#F8F5EF",
          overlay: "#F3EFE6",
          quarter: "#F8F5EF",
          swoosh: "#F3EFE6",
          midsole: "#F8F5EF",
          outsole: "#E7E0D4",
          lace: "#F8F5EF",
          collar: "#F3EFE6",
          tongue: "#F8F5EF",
          toe: "#F8F5EF",
          lining: "#EDE8DE",
        },
      },
      {
        id: "black",
        label: "Black",
        swatch: "#171717",
        palette: {
          upper: "#171717",
          overlay: "#0A0A0A",
          quarter: "#171717",
          swoosh: "#0A0A0A",
          midsole: "#171717",
          outsole: "#0A0A0A",
          lace: "#171717",
          collar: "#0A0A0A",
          tongue: "#171717",
          toe: "#171717",
          lining: "#262626",
        },
      },
      {
        id: "wheat",
        label: "Wheat",
        swatch: "#C4A574",
        palette: {
          upper: "#C4A574",
          overlay: "#A8844E",
          quarter: "#C4A574",
          swoosh: "#A8844E",
          midsole: "#D4B896",
          outsole: "#8B6914",
          lace: "#E8D5B5",
          collar: "#A8844E",
          tongue: "#C4A574",
          toe: "#D4B896",
          lining: "#8B6914",
        },
      },
    ],
  },
  {
    id: "dunk",
    name: "Dunk Low",
    colorway: "Panda",
    year: "1985",
    price: "¥899",
    category: "滑板",
    silhouette: "dunk",
    blurb: "校园配色进化成街头符号。低帮厚领、扁平外底，左右拖动能看见熊猫块面。",
    facts: ["低帮厚领", "块面拼接", "平底抓地"],
    colorways: [
      {
        id: "panda",
        label: "Panda",
        swatch: "#111111",
        palette: {
          upper: "#F7F4EE",
          overlay: "#111111",
          quarter: "#111111",
          swoosh: "#111111",
          midsole: "#F7F4EE",
          outsole: "#111111",
          lace: "#F7F4EE",
          collar: "#111111",
          tongue: "#F7F4EE",
          toe: "#111111",
          lining: "#1A1A1A",
        },
      },
      {
        id: "unc",
        label: "University Blue",
        swatch: "#7DD3FC",
        palette: {
          upper: "#F7F4EE",
          overlay: "#38BDF8",
          quarter: "#38BDF8",
          swoosh: "#0EA5E9",
          midsole: "#F7F4EE",
          outsole: "#0369A1",
          lace: "#F7F4EE",
          collar: "#38BDF8",
          tongue: "#E0F2FE",
          toe: "#38BDF8",
          lining: "#0C4A6E",
        },
      },
      {
        id: "vintage",
        label: "Vintage Green",
        swatch: "#3F6212",
        palette: {
          upper: "#F4EFE4",
          overlay: "#4D7C0F",
          quarter: "#4D7C0F",
          swoosh: "#365314",
          midsole: "#F4EFE4",
          outsole: "#1A2E05",
          lace: "#F4EFE4",
          collar: "#365314",
          tongue: "#ECFCCB",
          toe: "#4D7C0F",
          lining: "#1A2E05",
        },
      },
    ],
  },
  {
    id: "am90",
    name: "Air Max 90",
    colorway: "Infrared",
    year: "1990",
    price: "¥1,099",
    category: "跑鞋",
    silhouette: "max90",
    blurb: "红外线泥护与可见气垫。绕到鞋跟，透明窗里的气室会跟着光线折射。",
    facts: ["可见气垫", "华夫外底", "泥护包裹"],
    colorways: [
      {
        id: "infrared",
        label: "Infrared",
        swatch: "#F43F5E",
        palette: {
          upper: "#D6D3D1",
          overlay: "#F43F5E",
          quarter: "#E7E5E4",
          swoosh: "#F43F5E",
          midsole: "#F8F5EF",
          outsole: "#F43F5E",
          lace: "#E7E5E4",
          collar: "#A8A29E",
          tongue: "#E7E5E4",
          toe: "#D6D3D1",
          lining: "#44403C",
          air: "#7DD3FC",
        },
      },
      {
        id: "triple-black",
        label: "Triple Black",
        swatch: "#0A0A0A",
        palette: {
          upper: "#171717",
          overlay: "#0A0A0A",
          quarter: "#262626",
          swoosh: "#404040",
          midsole: "#171717",
          outsole: "#0A0A0A",
          lace: "#171717",
          collar: "#0A0A0A",
          tongue: "#262626",
          toe: "#171717",
          lining: "#404040",
          air: "#67E8F9",
        },
      },
      {
        id: "bacon",
        label: "Bacon",
        swatch: "#B91C1C",
        palette: {
          upper: "#F8F5EF",
          overlay: "#B91C1C",
          quarter: "#F8F5EF",
          swoosh: "#B91C1C",
          midsole: "#F8F5EF",
          outsole: "#7F1D1D",
          lace: "#F8F5EF",
          collar: "#B91C1C",
          tongue: "#FEE2E2",
          toe: "#F8F5EF",
          lining: "#7F1D1D",
          air: "#7DD3FC",
        },
      },
    ],
  },
  {
    id: "am1",
    name: "Air Max 1",
    colorway: "Anniversary",
    year: "1987",
    price: "¥1,199",
    category: "跑鞋",
    silhouette: "max1",
    blurb: "第一双把气垫亮到外面的跑鞋。大窗气室是这双鞋的环视焦点。",
    facts: ["大窗气垫", "华夫抓地", "复古跑鞋"],
    colorways: [
      {
        id: "anni",
        label: "Anniversary",
        swatch: "#B91C1C",
        palette: {
          upper: "#D6D3D1",
          overlay: "#B91C1C",
          quarter: "#E7E5E4",
          swoosh: "#B91C1C",
          midsole: "#F8F5EF",
          outsole: "#44403C",
          lace: "#E7E5E4",
          collar: "#A8A29E",
          tongue: "#E7E5E4",
          toe: "#D6D3D1",
          lining: "#44403C",
          air: "#7DD3FC",
        },
      },
      {
        id: "grey",
        label: "White / Grey",
        swatch: "#A8A29E",
        palette: {
          upper: "#E7E5E4",
          overlay: "#A8A29E",
          quarter: "#F5F5F4",
          swoosh: "#78716C",
          midsole: "#F8F5EF",
          outsole: "#57534E",
          lace: "#F5F5F4",
          collar: "#A8A29E",
          tongue: "#F5F5F4",
          toe: "#E7E5E4",
          lining: "#44403C",
          air: "#67E8F9",
        },
      },
      {
        id: "og-red",
        label: "OG Red",
        swatch: "#DC2626",
        palette: {
          upper: "#E7E5E4",
          overlay: "#DC2626",
          quarter: "#F5F5F4",
          swoosh: "#DC2626",
          midsole: "#F8F5EF",
          outsole: "#111111",
          lace: "#F5F5F4",
          collar: "#A8A29E",
          tongue: "#FEE2E2",
          toe: "#E7E5E4",
          lining: "#7F1D1D",
          air: "#7DD3FC",
        },
      },
    ],
  },
  {
    id: "blazer",
    name: "Blazer Mid '77",
    colorway: "Vintage",
    year: "1973",
    price: "¥859",
    category: "复古",
    silhouette: "blazer",
    blurb: "篮球馆里最早的高帮之一。更薄的杯底、加长鞋舌，旋转时能看到复古溢胶。",
    facts: ["加长鞋舌", "溢胶中底", "高帮帆布"],
    colorways: [
      {
        id: "vintage",
        label: "Vintage",
        swatch: "#166534",
        palette: {
          upper: "#F8F5EF",
          overlay: "#166534",
          quarter: "#F8F5EF",
          swoosh: "#166534",
          midsole: "#F4EFE4",
          outsole: "#44403C",
          lace: "#F8F5EF",
          collar: "#F8F5EF",
          tongue: "#F8F5EF",
          toe: "#F8F5EF",
          lining: "#14532D",
        },
      },
      {
        id: "jumbo",
        label: "Jumbo White",
        swatch: "#F8F5EF",
        palette: {
          upper: "#F8F5EF",
          overlay: "#111111",
          quarter: "#F8F5EF",
          swoosh: "#111111",
          midsole: "#F4EFE4",
          outsole: "#111111",
          lace: "#111111",
          collar: "#F8F5EF",
          tongue: "#F8F5EF",
          toe: "#F8F5EF",
          lining: "#262626",
        },
      },
      {
        id: "black",
        label: "Black",
        swatch: "#171717",
        palette: {
          upper: "#171717",
          overlay: "#F8F5EF",
          quarter: "#171717",
          swoosh: "#F8F5EF",
          midsole: "#F4EFE4",
          outsole: "#111111",
          lace: "#F8F5EF",
          collar: "#171717",
          tongue: "#171717",
          toe: "#171717",
          lining: "#262626",
        },
      },
    ],
  },
];
